/* tslint:disable */
/* eslint-disable */
/**
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers\' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.40
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Options to configure penalties for specific road categories or road types.
 * Penalties influence the route calculation by making certain roads more or less attractive.
 * Use these parameters carefully, in particular negative or blocking values can lead to unwanted results.
 * 
 * **Value ranges:**
 * * `-99` to `-1` — Preference (makes the road more attractive)
 * * `0` — No effect (default)
 * * `1` to `2500` — Avoidance (makes the road less attractive, higher = stronger avoidance)
 * * `2501` — Blocked (road is prohibited, may cause violations if no alternative exists, in particular when a waypoint is located on such a road)
 * 
 * All penalties except for **byRoadCategory**, **ferries** and **railShuttles** will be ignored for non-motorized profiles such as _BICYCLE_ or _PEDESTRIAN_.
 * 
 * Behavior for requests with **routeId**: When a **routeId** is specified, all penalties are ignored.
 * 
 * Behavior for **routingMode** _MONETARY_: As route calculation is optimized for costs, penalties have no effect.
 * Therefore, only the values 0 (roads are allowed) and 2501 (roads are blocked) are supported. All other values are ignored.
 * 
 * Behavior for **options[avoid]**: When both **options[avoid]** and a penalty are specified for the same road type, the request is rejected with an error.
 * 
 * See [here](./concepts/penalties) for more information.
 * @export
 * @interface PenaltyOptions
 */
export interface PenaltyOptions {
    /**
     * Penalty values per road category [8 elements].
     * The first element represents motorways, the last one pedestrian and cycle paths.
     * See [here](../data-api/concepts/road-categories) for more information on road categories.
     * Cannot be used together with **options[avoid]=HIGHWAYS** or **options[routingMode]=SHORTEST**.
     * 
     * Example: `[0,0,15,35,100,255,1000,1000]`
     * @type {Array<number>}
     * @memberof PenaltyOptions
     */
    byRoadCategory?: Array<number>;
    /**
     * Penalty for roads that are restricted to delivery vehicles only. The value 2501 is currently not supported.
     * @type {number}
     * @memberof PenaltyOptions
     */
    deliveryOnly?: number;
    /**
     * Penalty for roads that are restricted to residents only.
     * @type {number}
     * @memberof PenaltyOptions
     */
    residentsOnly?: number;
    /**
     * Penalty for toll roads. Cannot be used together with **options[avoid]=TOLL**.
     * @type {number}
     * @memberof PenaltyOptions
     */
    toll?: number;
    /**
     * Penalty for ferries. Cannot be used together with **options[avoid]=FERRIES**.
     * @type {number}
     * @memberof PenaltyOptions
     */
    ferries?: number;
    /**
     * Penalty for rail shuttles. Cannot be used together with **options[avoid]=RAIL_SHUTTLES**.
     * @type {number}
     * @memberof PenaltyOptions
     */
    railShuttles?: number;
}

/**
 * Check if a given object implements the PenaltyOptions interface.
 */
export function instanceOfPenaltyOptions(value: object): value is PenaltyOptions {
    return true;
}

export function PenaltyOptionsFromJSON(json: any): PenaltyOptions {
    return PenaltyOptionsFromJSONTyped(json, false);
}

export function PenaltyOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PenaltyOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'byRoadCategory': json['byRoadCategory'] == null ? undefined : json['byRoadCategory'],
        'deliveryOnly': json['deliveryOnly'] == null ? undefined : json['deliveryOnly'],
        'residentsOnly': json['residentsOnly'] == null ? undefined : json['residentsOnly'],
        'toll': json['toll'] == null ? undefined : json['toll'],
        'ferries': json['ferries'] == null ? undefined : json['ferries'],
        'railShuttles': json['railShuttles'] == null ? undefined : json['railShuttles'],
    };
}

export function PenaltyOptionsToJSON(value?: PenaltyOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'byRoadCategory': value['byRoadCategory'],
        'deliveryOnly': value['deliveryOnly'],
        'residentsOnly': value['residentsOnly'],
        'toll': value['toll'],
        'ferries': value['ferries'],
        'railShuttles': value['railShuttles'],
    };
}

