/*
 * Routing
 *
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.40
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.Model
{
    /// <summary>
    /// Options to configure penalties for specific road categories or road types. Penalties influence the route calculation by making certain roads more or less attractive. Use these parameters carefully, in particular negative or blocking values can lead to unwanted results.  **Value ranges:** * &#x60;-99&#x60; to &#x60;-1&#x60; — Preference (makes the road more attractive) * &#x60;0&#x60; — No effect (default) * &#x60;1&#x60; to &#x60;2500&#x60; — Avoidance (makes the road less attractive, higher &#x3D; stronger avoidance) * &#x60;2501&#x60; — Blocked (road is prohibited, may cause violations if no alternative exists, in particular when a waypoint is located on such a road)  All penalties except for **byRoadCategory**, **ferries** and **railShuttles** will be ignored for non-motorized profiles such as _BICYCLE_ or _PEDESTRIAN_.  Behavior for requests with **routeId**: When a **routeId** is specified, all penalties are ignored.  Behavior for **routingMode** _MONETARY_: As route calculation is optimized for costs, penalties have no effect. Therefore, only the values 0 (roads are allowed) and 2501 (roads are blocked) are supported. All other values are ignored.  Behavior for **options[avoid]**: When both **options[avoid]** and a penalty are specified for the same road type, the request is rejected with an error.  See [here](./concepts/penalties) for more information.
    /// </summary>
    [DataContract(Name = "PenaltyOptions")]
    public partial class PenaltyOptions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PenaltyOptions" /> class.
        /// </summary>
        /// <param name="byRoadCategory">Penalty values per road category [8 elements]. The first element represents motorways, the last one pedestrian and cycle paths. See [here](../data-api/concepts/road-categories) for more information on road categories. Cannot be used together with **options[avoid]&#x3D;HIGHWAYS** or **options[routingMode]&#x3D;SHORTEST**.  Example: &#x60;[0,0,15,35,100,255,1000,1000]&#x60;.</param>
        /// <param name="deliveryOnly">Penalty for roads that are restricted to delivery vehicles only. The value 2501 is currently not supported..</param>
        /// <param name="residentsOnly">Penalty for roads that are restricted to residents only..</param>
        /// <param name="toll">Penalty for toll roads. Cannot be used together with **options[avoid]&#x3D;TOLL**..</param>
        /// <param name="ferries">Penalty for ferries. Cannot be used together with **options[avoid]&#x3D;FERRIES**..</param>
        /// <param name="railShuttles">Penalty for rail shuttles. Cannot be used together with **options[avoid]&#x3D;RAIL_SHUTTLES**..</param>
        public PenaltyOptions(List<int?> byRoadCategory = default(List<int?>), int? deliveryOnly = default(int?), int? residentsOnly = default(int?), int? toll = default(int?), int? ferries = default(int?), int? railShuttles = default(int?))
        {
            this.ByRoadCategory = byRoadCategory;
            this.DeliveryOnly = deliveryOnly;
            this.ResidentsOnly = residentsOnly;
            this.Toll = toll;
            this.Ferries = ferries;
            this.RailShuttles = railShuttles;
        }

        /// <summary>
        /// Penalty values per road category [8 elements]. The first element represents motorways, the last one pedestrian and cycle paths. See [here](../data-api/concepts/road-categories) for more information on road categories. Cannot be used together with **options[avoid]&#x3D;HIGHWAYS** or **options[routingMode]&#x3D;SHORTEST**.  Example: &#x60;[0,0,15,35,100,255,1000,1000]&#x60;
        /// </summary>
        /// <value>Penalty values per road category [8 elements]. The first element represents motorways, the last one pedestrian and cycle paths. See [here](../data-api/concepts/road-categories) for more information on road categories. Cannot be used together with **options[avoid]&#x3D;HIGHWAYS** or **options[routingMode]&#x3D;SHORTEST**.  Example: &#x60;[0,0,15,35,100,255,1000,1000]&#x60;</value>
        [DataMember(Name = "byRoadCategory", EmitDefaultValue = false)]
        public List<int?> ByRoadCategory { get; set; }

        /// <summary>
        /// Penalty for roads that are restricted to delivery vehicles only. The value 2501 is currently not supported.
        /// </summary>
        /// <value>Penalty for roads that are restricted to delivery vehicles only. The value 2501 is currently not supported.</value>
        [DataMember(Name = "deliveryOnly", EmitDefaultValue = true)]
        public int? DeliveryOnly { get; set; }

        /// <summary>
        /// Penalty for roads that are restricted to residents only.
        /// </summary>
        /// <value>Penalty for roads that are restricted to residents only.</value>
        [DataMember(Name = "residentsOnly", EmitDefaultValue = true)]
        public int? ResidentsOnly { get; set; }

        /// <summary>
        /// Penalty for toll roads. Cannot be used together with **options[avoid]&#x3D;TOLL**.
        /// </summary>
        /// <value>Penalty for toll roads. Cannot be used together with **options[avoid]&#x3D;TOLL**.</value>
        [DataMember(Name = "toll", EmitDefaultValue = true)]
        public int? Toll { get; set; }

        /// <summary>
        /// Penalty for ferries. Cannot be used together with **options[avoid]&#x3D;FERRIES**.
        /// </summary>
        /// <value>Penalty for ferries. Cannot be used together with **options[avoid]&#x3D;FERRIES**.</value>
        [DataMember(Name = "ferries", EmitDefaultValue = true)]
        public int? Ferries { get; set; }

        /// <summary>
        /// Penalty for rail shuttles. Cannot be used together with **options[avoid]&#x3D;RAIL_SHUTTLES**.
        /// </summary>
        /// <value>Penalty for rail shuttles. Cannot be used together with **options[avoid]&#x3D;RAIL_SHUTTLES**.</value>
        [DataMember(Name = "railShuttles", EmitDefaultValue = true)]
        public int? RailShuttles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PenaltyOptions {\n");
            sb.Append("  ByRoadCategory: ").Append(ByRoadCategory).Append("\n");
            sb.Append("  DeliveryOnly: ").Append(DeliveryOnly).Append("\n");
            sb.Append("  ResidentsOnly: ").Append(ResidentsOnly).Append("\n");
            sb.Append("  Toll: ").Append(Toll).Append("\n");
            sb.Append("  Ferries: ").Append(Ferries).Append("\n");
            sb.Append("  RailShuttles: ").Append(RailShuttles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DeliveryOnly (int?) maximum
            if (this.DeliveryOnly > (int?)2500)
            {
                yield return new ValidationResult("Invalid value for DeliveryOnly, must be a value less than or equal to 2500.", new [] { "DeliveryOnly" });
            }

            // DeliveryOnly (int?) minimum
            if (this.DeliveryOnly < (int?)-99)
            {
                yield return new ValidationResult("Invalid value for DeliveryOnly, must be a value greater than or equal to -99.", new [] { "DeliveryOnly" });
            }

            // ResidentsOnly (int?) maximum
            if (this.ResidentsOnly > (int?)2501)
            {
                yield return new ValidationResult("Invalid value for ResidentsOnly, must be a value less than or equal to 2501.", new [] { "ResidentsOnly" });
            }

            // ResidentsOnly (int?) minimum
            if (this.ResidentsOnly < (int?)-99)
            {
                yield return new ValidationResult("Invalid value for ResidentsOnly, must be a value greater than or equal to -99.", new [] { "ResidentsOnly" });
            }

            // Toll (int?) maximum
            if (this.Toll > (int?)2501)
            {
                yield return new ValidationResult("Invalid value for Toll, must be a value less than or equal to 2501.", new [] { "Toll" });
            }

            // Toll (int?) minimum
            if (this.Toll < (int?)-99)
            {
                yield return new ValidationResult("Invalid value for Toll, must be a value greater than or equal to -99.", new [] { "Toll" });
            }

            // Ferries (int?) maximum
            if (this.Ferries > (int?)2501)
            {
                yield return new ValidationResult("Invalid value for Ferries, must be a value less than or equal to 2501.", new [] { "Ferries" });
            }

            // Ferries (int?) minimum
            if (this.Ferries < (int?)-99)
            {
                yield return new ValidationResult("Invalid value for Ferries, must be a value greater than or equal to -99.", new [] { "Ferries" });
            }

            // RailShuttles (int?) maximum
            if (this.RailShuttles > (int?)2501)
            {
                yield return new ValidationResult("Invalid value for RailShuttles, must be a value less than or equal to 2501.", new [] { "RailShuttles" });
            }

            // RailShuttles (int?) minimum
            if (this.RailShuttles < (int?)-99)
            {
                yield return new ValidationResult("Invalid value for RailShuttles, must be a value greater than or equal to -99.", new [] { "RailShuttles" });
            }

            yield break;
        }
    }

}
