/*
 * Routing
 * With the Routing service you can calculate routes from A to B taking into account vehicle-specific restrictions, traffic situations, toll, emissions, drivers' working hours, service times and opening intervals.
 *
 * The version of the OpenAPI document: 1.40
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routing.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.routing.ApiClient;
/**
 * Options to configure penalties for specific road categories or road types. Penalties influence the route calculation by making certain roads more or less attractive. Use these parameters carefully, in particular negative or blocking values can lead to unwanted results.  **Value ranges:** * &#x60;-99&#x60; to &#x60;-1&#x60; — Preference (makes the road more attractive) * &#x60;0&#x60; — No effect (default) * &#x60;1&#x60; to &#x60;2500&#x60; — Avoidance (makes the road less attractive, higher &#x3D; stronger avoidance) * &#x60;2501&#x60; — Blocked (road is prohibited, may cause violations if no alternative exists, in particular when a waypoint is located on such a road)  All penalties except for **byRoadCategory**, **ferries** and **railShuttles** will be ignored for non-motorized profiles such as _BICYCLE_ or _PEDESTRIAN_.  Behavior for requests with **routeId**: When a **routeId** is specified, all penalties are ignored.  Behavior for **routingMode** _MONETARY_: As route calculation is optimized for costs, penalties have no effect. Therefore, only the values 0 (roads are allowed) and 2501 (roads are blocked) are supported. All other values are ignored.  Behavior for **options[avoid]**: When both **options[avoid]** and a penalty are specified for the same road type, the request is rejected with an error.  See [here](./concepts/penalties) for more information.
 */
@JsonPropertyOrder({
  PenaltyOptions.JSON_PROPERTY_BY_ROAD_CATEGORY,
  PenaltyOptions.JSON_PROPERTY_DELIVERY_ONLY,
  PenaltyOptions.JSON_PROPERTY_RESIDENTS_ONLY,
  PenaltyOptions.JSON_PROPERTY_TOLL,
  PenaltyOptions.JSON_PROPERTY_FERRIES,
  PenaltyOptions.JSON_PROPERTY_RAIL_SHUTTLES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-23T10:51:26.489242051Z[Etc/UTC]", comments = "Generator version: 7.8.0")
public class PenaltyOptions {
  public static final String JSON_PROPERTY_BY_ROAD_CATEGORY = "byRoadCategory";
  private List<Integer> byRoadCategory;

  public static final String JSON_PROPERTY_DELIVERY_ONLY = "deliveryOnly";
  private Integer deliveryOnly;

  public static final String JSON_PROPERTY_RESIDENTS_ONLY = "residentsOnly";
  private Integer residentsOnly;

  public static final String JSON_PROPERTY_TOLL = "toll";
  private Integer toll;

  public static final String JSON_PROPERTY_FERRIES = "ferries";
  private Integer ferries;

  public static final String JSON_PROPERTY_RAIL_SHUTTLES = "railShuttles";
  private Integer railShuttles;

  public PenaltyOptions() { 
  }

  public PenaltyOptions byRoadCategory(List<Integer> byRoadCategory) {
    this.byRoadCategory = byRoadCategory;
    return this;
  }

  public PenaltyOptions addByRoadCategoryItem(Integer byRoadCategoryItem) {
    if (this.byRoadCategory == null) {
      this.byRoadCategory = new ArrayList<>();
    }
    this.byRoadCategory.add(byRoadCategoryItem);
    return this;
  }

  /**
   * Penalty values per road category [8 elements]. The first element represents motorways, the last one pedestrian and cycle paths. See [here](../data-api/concepts/road-categories) for more information on road categories. Cannot be used together with **options[avoid]&#x3D;HIGHWAYS** or **options[routingMode]&#x3D;SHORTEST**.  Example: &#x60;[0,0,15,35,100,255,1000,1000]&#x60;
   * @return byRoadCategory
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BY_ROAD_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Integer> getByRoadCategory() {
    return byRoadCategory;
  }


  @JsonProperty(JSON_PROPERTY_BY_ROAD_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setByRoadCategory(List<Integer> byRoadCategory) {
    this.byRoadCategory = byRoadCategory;
  }


  public PenaltyOptions deliveryOnly(Integer deliveryOnly) {
    this.deliveryOnly = deliveryOnly;
    return this;
  }

  /**
   * Penalty for roads that are restricted to delivery vehicles only. The value 2501 is currently not supported.
   * minimum: -99
   * maximum: 2500
   * @return deliveryOnly
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDeliveryOnly() {
    return deliveryOnly;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryOnly(Integer deliveryOnly) {
    this.deliveryOnly = deliveryOnly;
  }


  public PenaltyOptions residentsOnly(Integer residentsOnly) {
    this.residentsOnly = residentsOnly;
    return this;
  }

  /**
   * Penalty for roads that are restricted to residents only.
   * minimum: -99
   * maximum: 2501
   * @return residentsOnly
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESIDENTS_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getResidentsOnly() {
    return residentsOnly;
  }


  @JsonProperty(JSON_PROPERTY_RESIDENTS_ONLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResidentsOnly(Integer residentsOnly) {
    this.residentsOnly = residentsOnly;
  }


  public PenaltyOptions toll(Integer toll) {
    this.toll = toll;
    return this;
  }

  /**
   * Penalty for toll roads. Cannot be used together with **options[avoid]&#x3D;TOLL**.
   * minimum: -99
   * maximum: 2501
   * @return toll
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getToll() {
    return toll;
  }


  @JsonProperty(JSON_PROPERTY_TOLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToll(Integer toll) {
    this.toll = toll;
  }


  public PenaltyOptions ferries(Integer ferries) {
    this.ferries = ferries;
    return this;
  }

  /**
   * Penalty for ferries. Cannot be used together with **options[avoid]&#x3D;FERRIES**.
   * minimum: -99
   * maximum: 2501
   * @return ferries
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FERRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFerries() {
    return ferries;
  }


  @JsonProperty(JSON_PROPERTY_FERRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFerries(Integer ferries) {
    this.ferries = ferries;
  }


  public PenaltyOptions railShuttles(Integer railShuttles) {
    this.railShuttles = railShuttles;
    return this;
  }

  /**
   * Penalty for rail shuttles. Cannot be used together with **options[avoid]&#x3D;RAIL_SHUTTLES**.
   * minimum: -99
   * maximum: 2501
   * @return railShuttles
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RAIL_SHUTTLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRailShuttles() {
    return railShuttles;
  }


  @JsonProperty(JSON_PROPERTY_RAIL_SHUTTLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRailShuttles(Integer railShuttles) {
    this.railShuttles = railShuttles;
  }


  /**
   * Return true if this PenaltyOptions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PenaltyOptions penaltyOptions = (PenaltyOptions) o;
    return Objects.equals(this.byRoadCategory, penaltyOptions.byRoadCategory) &&
        Objects.equals(this.deliveryOnly, penaltyOptions.deliveryOnly) &&
        Objects.equals(this.residentsOnly, penaltyOptions.residentsOnly) &&
        Objects.equals(this.toll, penaltyOptions.toll) &&
        Objects.equals(this.ferries, penaltyOptions.ferries) &&
        Objects.equals(this.railShuttles, penaltyOptions.railShuttles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byRoadCategory, deliveryOnly, residentsOnly, toll, ferries, railShuttles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PenaltyOptions {\n");
    sb.append("    byRoadCategory: ").append(toIndentedString(byRoadCategory)).append("\n");
    sb.append("    deliveryOnly: ").append(toIndentedString(deliveryOnly)).append("\n");
    sb.append("    residentsOnly: ").append(toIndentedString(residentsOnly)).append("\n");
    sb.append("    toll: ").append(toIndentedString(toll)).append("\n");
    sb.append("    ferries: ").append(toIndentedString(ferries)).append("\n");
    sb.append("    railShuttles: ").append(toIndentedString(railShuttles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `byRoadCategory` to the URL query string
    if (getByRoadCategory() != null) {
      for (int i = 0; i < getByRoadCategory().size(); i++) {
        joiner.add(String.format("%sbyRoadCategory%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getByRoadCategory().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `deliveryOnly` to the URL query string
    if (getDeliveryOnly() != null) {
      joiner.add(String.format("%sdeliveryOnly%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDeliveryOnly()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `residentsOnly` to the URL query string
    if (getResidentsOnly() != null) {
      joiner.add(String.format("%sresidentsOnly%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getResidentsOnly()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `toll` to the URL query string
    if (getToll() != null) {
      joiner.add(String.format("%stoll%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getToll()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ferries` to the URL query string
    if (getFerries() != null) {
      joiner.add(String.format("%sferries%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFerries()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `railShuttles` to the URL query string
    if (getRailShuttles() != null) {
      joiner.add(String.format("%srailShuttles%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRailShuttles()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

